============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /home/antonio/workspace/pyco/pyco, inifile:
plugins: timeout-1.3.2
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_eps_facs.py Decomposing Specification...
Process MultipleOutputProcessor-7:
Process MultipleOutputProcessor-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    output, unused_err = process.communicate()
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
	multiple output clusters, processing port c7
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
	multiple output clusters, processing port c3
Process MultipleOutputProcessor-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultipleOutputProcessor-4:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    self.run()
Process MultipleOutputProcessor-5:
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultipleOutputProcessor-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    return_trace=return_trace)
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    output, unused_err = process.communicate()
Process MultipleOutputProcessor-1:
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
    stdout = _eintr_retry_call(self.stdout.read)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
Process MultipleOutputProcessor-8:
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
Traceback (most recent call last):
    return func(*args)
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
KeyboardInterrupt
    stderr=STDOUT, )
Traceback (most recent call last):
Process MultipleOutputProcessor-6:
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    output, unused_err = process.communicate()
	multiple output clusters, processing port c4
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
KeyboardInterrupt
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    self.run()
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
	multiple output clusters, processing port c2
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
KeyboardInterrupt
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
	multiple output clusters, processing port c1
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
KeyboardInterrupt
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
	multiple output clusters, processing port c5
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
    output, unused_err = process.communicate()
KeyboardInterrupt
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
    output, unused_err = process.communicate()
	multiple output clusters, processing port c9
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
	multiple output clusters, processing port c10
KeyboardInterrupt
	multiple output clusters, processing port c6


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/usr/lib/python2.7/multiprocessing/forking.py:135: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --fulltrace)
========================= no tests ran in 8.03 seconds =========================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
Process MultipleOutputProcessor-2:
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
Traceback (most recent call last):
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
    self.run()
  File "/home/antonio/workspace/pyco/pyco/spec_decomposition.py", line 195, in run
    l_passed, trace = verify_tautology(ref_formula, return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
	multiple output clusters, processing port c8
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /home/antonio/workspace/pyco/pyco, inifile:
plugins: timeout-1.3.2
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_eps_facs.py Decomposing Specification...
	multiple output clusters, processing port c2
	multiple output clusters, processing port c9
	multiple output clusters, processing port c3
	multiple output clusters, processing port c7
	multiple output clusters, processing port c10
	multiple output clusters, processing port c5
	multiple output clusters, processing port c8
	multiple output clusters, processing port c6
	multiple output clusters, processing port c4
	multiple output clusters, processing port c1
Instantiate Solvers...
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
40
* 
loops until success:
1

* 
loops until success:
1

* 
loops until success:
1

* 
loops until success:
1
* 
loops until success:
1


* 
loops until success:
1

* 
loops until success:
1

* 
loops until success:
1

* 
loops until success:
1
* 
loops until success:
1


.

========================== 1 passed in 16.80 seconds ===========================
